// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Drug struct {
	DrugID            uuid.UUID `json:"drug_id"`
	PharmacyBranchID  uuid.UUID `json:"pharmacy_branch_id"`
	BrandName         string    `json:"brand_name"`
	GenericName       string    `json:"generic_name"`
	Quantity          int64     `json:"quantity"`
	ExpirationDate    time.Time `json:"expiration_date"`
	ManufacturingDate time.Time `json:"manufacturing_date"`
	PharmacistID      uuid.UUID `json:"pharmacist_id"`
	AddedAt           time.Time `json:"added_at"`
}

type Pharmacist struct {
	PharmacistID     uuid.UUID `json:"pharmacist_id"`
	PharmacyBranchID uuid.UUID `json:"pharmacy_branch_id"`
	Username         string    `json:"username"`
	Password         string    `json:"password"`
	Email            string    `json:"email"`
	Role             string    `json:"role"`
	CreatedAt        time.Time `json:"created_at"`
}

type PharmacistSession struct {
	SessionID    uuid.UUID `json:"session_id"`
	PharmacistID uuid.UUID `json:"pharmacist_id"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Pharmacy struct {
	PharmacyID   uuid.UUID `json:"pharmacy_id"`
	PharmacyName string    `json:"pharmacy_name"`
	UserID       uuid.UUID `json:"user_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type PharmacyBranch struct {
	PharmacyBranchID    uuid.UUID `json:"pharmacy_branch_id"`
	PharmacyID          uuid.UUID `json:"pharmacy_id"`
	PharmacyBranchName  string    `json:"pharmacy_branch_name"`
	City                string    `json:"city"`
	SubCity             string    `json:"sub_city"`
	SpecialLocationName string    `json:"special_location_name"`
	CreatedAt           time.Time `json:"created_at"`
}

type User struct {
	UserID    uuid.UUID `json:"user_id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type UserSession struct {
	SessionID    uuid.UUID `json:"session_id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}
