// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDrug(ctx context.Context, arg CreateDrugParams) (Drug, error)
	CreatePharmacist(ctx context.Context, arg CreatePharmacistParams) (Pharmacist, error)
	CreatePharmacy(ctx context.Context, arg CreatePharmacyParams) (Pharmacy, error)
	CreatePharmacyBranch(ctx context.Context, arg CreatePharmacyBranchParams) (PharmacyBranch, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	DeleteUserSession(ctx context.Context, userID uuid.UUID) error
	GetPharmacist(ctx context.Context, pharmacistID uuid.UUID) (Pharmacist, error)
	GetPharmacy(ctx context.Context, pharmacyID uuid.UUID) (Pharmacy, error)
	GetPharmacyBrachByName(ctx context.Context, pharmacyBranchName string) (PharmacyBranch, error)
	GetPharmacyByAdminID(ctx context.Context, userID uuid.UUID) (Pharmacy, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserSession(ctx context.Context, sessionID uuid.UUID) (UserSession, error)
}

var _ Querier = (*Queries)(nil)
